apiVersion: v1
kind: Secret
metadata:
  name: pulse-monitoring-secret
type: Opaque
data:
 karafkaPassword: M0JVT1I0eUh3SUFyUGUzdnFlY2pIM1Q4ZnJCakRiVXM=
 redisPassword: ZnFERW1XUDNwdllBQzVTMGYxS0FWUW92Tm9JaktOUWc=
 mongoPassword: MTIzNDUuY29t
 postgresqlPassword: QzBkZmE1cHBlTXU4Qzl6eHZqdEZXOTlJVzlRSzMxaWU=
 mailPassword: YnRlc3loZmR5amhsYWN3bA==
 jwtSecret: YWFlNzc5YjVjMjIwNDYwZGRmZGZiZDIzMzNjZTY2ZTIyYTZmNmY1NDlkZWE0MjhjNDNiZDY5M2ZiOWI1ZDVlMw==
 adminPassword: YWRtaW4xMjM0
